### Array types and conversion between types

In [1]:
import numpy as np

In [2]:
integers = np.array([1,2,3,4,5])
print(integers)

[1 2 3 4 5]


In [3]:
integers[0]

1

In [5]:
integers[0]=2
integers

array([2, 2, 3, 4, 5])

In [6]:
integers.dtype

dtype('int32')

In [10]:
smallintegers= np.array(integers, dtype=np.int8)
smallintegers

array([2, 2, 3, 4, 5], dtype=int8)

In [11]:
smallintegers.dtype

dtype('int8')

In [12]:
floats = np.array([1.1,1.2,1.3,1.4])
floats.dtype

dtype('float64')

### Multidimension Arrays

In [14]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]]


2

In [15]:
matrix[0][1]

2

In [16]:
matrix[1][2]

6

In [18]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
tensor[0,0,1]

2

In [20]:
tensor[1,1,1]

8

In [21]:
tensor.ndim

3

### Creating arrays from lists and other Python Structure

In [25]:
firstlist= [1,2,3,4,5,6,7,8]
firstlists = np.array([firstlist])
firstlists

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [27]:
secondlist= [1,1.2, -1.456, 2345.67]
secondlists=np.array(secondlist)
secondlists

array([ 1.00000e+00,  1.20000e+00, -1.45600e+00,  2.34567e+03])

In [28]:
secondlists.dtype

dtype('float64')

In [31]:
thirdlist= ['peter', 102, 'paul', 34.56, 'thor', -456]
type(thirdlist)

list

In [33]:
thirdlists= np.array(thirdlist)
thirdlists

array(['peter', '102', 'paul', '34.56', 'thor', '-456'], dtype='<U32')

In [34]:
thirdlists.dtype

dtype('<U32')

In [39]:
first_tuple = (1,2,3,4,5,6)
first_tuples= np.array(first_tuple)
first_tuples.ndim

1

In [41]:
second_tuple= ([[1,2,3],[4,5,6]])
second = np.array(second_tuple)
second

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
second.ndim

2

### Intrinsic Numpy Array Creation

In [45]:
list=np.arange(10)
list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [48]:
num = np.arange(10,20)
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [51]:
even = np.arange(0,11,2)
even

array([ 0,  2,  4,  6,  8, 10])

In [56]:
# For floating numbers
floats= np.linspace(10,20)
floats

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [58]:
# Specify the numbers you need
floats = np.linspace(10,20,5)
floats

array([10. , 12.5, 15. , 17.5, 20. ])

In [59]:
# To generate random numbers
random = np.random.rand(10)
random

array([0.44836727, 0.05012619, 0.61551317, 0.20949211, 0.0777435 ,
       0.71465609, 0.47070332, 0.34556818, 0.86856292, 0.53192755])

In [65]:
random1 = np.random.rand(3,20,10)
random1

array([[[0.26776754, 0.08443154, 0.00168775, 0.40000418, 0.39919545,
         0.10668627, 0.07920509, 0.53285239, 0.894218  , 0.72642643],
        [0.74937644, 0.3218493 , 0.10877631, 0.56558395, 0.64760845,
         0.19683018, 0.39922047, 0.9815178 , 0.72896337, 0.10226741],
        [0.7627688 , 0.90920889, 0.84297022, 0.58353935, 0.3116896 ,
         0.38008419, 0.34321911, 0.33932018, 0.85405895, 0.95676589],
        [0.9873785 , 0.76957673, 0.31575728, 0.37060954, 0.02807145,
         0.47667615, 0.1189901 , 0.57750633, 0.17245001, 0.85538172],
        [0.96949458, 0.4715869 , 0.48399522, 0.55351646, 0.01929603,
         0.91877517, 0.68024142, 0.40922615, 0.27664162, 0.13345333],
        [0.28764011, 0.59413137, 0.48248014, 0.04021798, 0.95955941,
         0.8769056 , 0.01178431, 0.02664831, 0.08686161, 0.69399553],
        [0.93036101, 0.12542786, 0.29218155, 0.0529384 , 0.24391716,
         0.13597046, 0.3440877 , 0.06411931, 0.42726334, 0.90541138],
        [0.0847292 , 0.5350

In [69]:
# To get the integer random numbers
num = np.random.randint(10,20,5)
num


array([12, 11, 17, 14, 16])

In [72]:
### Creating arrays filled with constant values
zeros = np.zeros(10, dtype = int)
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
zeros = np.zeros((4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [78]:
ones= np.ones((2,3),dtype = int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [80]:
# Create empty list and then fill it with 4
empty = np.empty(10, dtype = int)
empty.fill(4)
empty

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [81]:
# 10 elements of 5 letter
full = np.full(10,5)
full

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [83]:
# create matrix of element 8
matrix = np.full((4,3),8)
matrix

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

### Finding shape and size of an array

In [86]:
first_arr = np.arange(10)
first_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
second_arr = np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [94]:
third_arr = np.full((2,2,3),4)
third_arr

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [95]:
np.shape(first_arr)

(10,)

In [99]:
np.shape(second_arr)

(10, 2)

In [97]:
np.shape(third_arr)

(2, 2, 3)

In [100]:
np.size(first_arr)

10

In [101]:
np.size(second_arr)

20

In [102]:
np.size(third_arr)

12

### Adding, removing and sorting element

In [105]:
# insert at specific point
first_arr = np.array([1,2,3,5])
new_first = np.insert(first_arr,3,4)
new_first

array([1, 2, 3, 4, 5])

In [106]:
# append adds element at the end
second_arr = np.array([1,2,3,4])
new_second = np.append(second_arr,5)
new_second

array([1, 2, 3, 4, 5])

In [110]:
# delete the element while specifies index
del_arr = np.delete(first_arr,3)
del_arr

array([1, 2, 3])

In [111]:
# sort the random numbers
integers = np.random.randint(0,20,20)
integers

array([ 7, 12, 15,  3, 13,  6,  2,  0,  3, 17, 17,  8,  0, 18, 14,  7,  9,
        7,  1,  6])

In [113]:
integers_arr= np.sort(integers)
integers_arr

array([ 0,  0,  1,  2,  3,  3,  6,  6,  7,  7,  7,  8,  9, 12, 13, 14, 15,
       17, 17, 18])