### Topic discussed
1. Filtering arrays
2. Aggregating arrays

### Filtering Arrays

In [15]:
#Filter the product array to only include with price greater than 25.
import numpy as np
prices= np.array([5.99,6.99,22.49,99.99,4.99,49.99])
product= np.array(['salad','bread','mustard','rare tomato','cola','gourmet ice-cream'])
product[prices > 25]

array(['rare tomato', 'gourmet ice-cream'], dtype='<U17')

In [12]:
mask = (prices > 25) | (product == 'cola')
mask

array([False, False, False,  True,  True,  True])

In [14]:
# include cola in your array. and name as fancy feast special.
fancy_feast_special = product[mask]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice-cream'], dtype='<U17')

In [19]:
# Next, create a shipping cost array where the cost is 0 when price is > 20 and 5 if not.
shipping_cost = np.where(prices > 20, 0,5)
shipping_cost

array([5, 5, 0, 0, 5, 0])

### Aggregating arrays

In [26]:
# generate two random arrays
from numpy.random import default_rng
rng = np.random.default_rng(616)
prices = (rng.random(10)*10).round(2)
prices

array([3.97, 8.66, 4.6 , 3.06, 5.74, 0.89, 8.82, 7.32, 7.32, 5.62])

In [28]:
inventory = rng.integers(0,100,10)
inventory

array([94, 10, 27, 52, 15, 80, 90,  7, 32, 15], dtype=int64)

In [38]:
(prices.sum(axis=0)).round(2)

56.0

In [40]:
# convert into 2d array
prices_2d= prices.reshape(5,2)
prices_2d

array([[3.97, 8.66],
       [4.6 , 3.06],
       [5.74, 0.89],
       [8.82, 7.32],
       [7.32, 5.62]])

#### Find sum, max,min,sort, median,percentile,unique.

In [44]:
prices_2d.max(axis=0)

array([8.82, 8.66])

In [46]:
(prices*inventory).sum()

2063.98

In [48]:
prices.sum()

56.0

In [49]:
inventory.sum()

422

In [51]:
product = (prices*inventory)
product

array([373.18,  86.6 , 124.2 , 159.12,  86.1 ,  71.2 , 793.8 ,  51.24,
       234.24,  84.3 ])

In [52]:
product.reshape(2,5)

array([[373.18,  86.6 , 124.2 , 159.12,  86.1 ],
       [ 71.2 , 793.8 ,  51.24, 234.24,  84.3 ]])

In [53]:
np.sort(product)

array([ 51.24,  71.2 ,  84.3 ,  86.1 ,  86.6 , 124.2 , 159.12, 234.24,
       373.18, 793.8 ])

In [54]:
np.median(product)

105.39999999999999

In [58]:
np.percentile(product, 90)

415.24199999999985

In [59]:
np.unique(np.ones(100))

array([1.])

In [62]:
np.sort(product)

array([ 51.24,  71.2 ,  84.3 ,  86.1 ,  86.6 , 124.2 , 159.12, 234.24,
       373.18, 793.8 ])

In [65]:
product.sort()

In [66]:
product

array([ 51.24,  71.2 ,  84.3 ,  86.1 ,  86.6 , 124.2 , 159.12, 234.24,
       373.18, 793.8 ])

In [69]:
product[::-1]

array([793.8 , 373.18, 234.24, 159.12, 124.2 ,  86.6 ,  86.1 ,  84.3 ,
        71.2 ,  51.24])

In [76]:
# first grab the first 3 items from list
prices= np.array([5.99,6.99,22.49,99.99,4.99,49.99])
sort=np.sort(prices)
sort

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [78]:
top3= sort[3:]
top3

array([22.49, 49.99, 99.99])

In [79]:
top3.mean()

57.49

In [80]:
top3.max()

99.99

In [81]:
top3.min()

22.49

In [83]:
np.median(top3)

49.99

In [84]:
np.unique(prices)

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])