### Numpy array and its properties

In [12]:
import numpy as np

In [13]:
array =  np.array(range(5))
print(array)
print('ndim :', array.ndim)
print('shape :', array.shape)
print('size :', array.size)
print('dtype :', array.dtype)

[0 1 2 3 4]
ndim : 1
shape : (5,)
size : 5
dtype : int32


In [11]:
array_2d= np.array([range(5), range(5)])
print(array_2d)
print(array_2d.T)
print('ndim :', array_2d.ndim)
print('shape :', array_2d.shape)
print('size :', array_2d.size)
print('dtype :', array_2d.dtype)

[[0 1 2 3 4]
 [0 1 2 3 4]]
[[0 0]
 [1 1]
 [2 2]
 [3 3]
 [4 4]]
ndim : 2
shape : (2, 5)
size : 10
dtype : int32


#### The nested portion should be of equal length

In [14]:
np.array(['I','Love','Python'])

array(['I', 'Love', 'Python'], dtype='<U6')

In [47]:
np.ones(10, dtype='int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
np.zeros((5,2)).reshape(1,10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [49]:
np.arange(10,115,10) #start,stop,step

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [37]:
np.linspace(10,20, 10).reshape(5,2)

array([[10.        , 11.11111111],
       [12.22222222, 13.33333333],
       [14.44444444, 15.55555556],
       [16.66666667, 17.77777778],
       [18.88888889, 20.        ]])

In [40]:
np.linspace(8,64,10, dtype= 'int')

array([ 8, 14, 20, 26, 32, 39, 45, 51, 57, 64])

### Random number generatorm

In [42]:
np.default_rng(5)

AttributeError: module 'numpy' has no attribute 'default_rng'

In [43]:
rng.random(5)

NameError: name 'rng' is not defined