### Topics discussed
1. Indexing and Slicing
2. Arithmetic Operator

### 1. Indexing and Slicing

In [10]:
from numpy.random import default_rng
import numpy as np
integers = np.arange(12)
integers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
integers[:5]

array([0, 1, 2, 3, 4])

In [12]:
integers[::2]

array([ 0,  2,  4,  6,  8, 10])

In [13]:
array_2d = integers.reshape(4,3)
array_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
array_2d[1:2,:]

array([[3, 4, 5]])

In [15]:
array_2d[:,1:2]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [16]:
#extract diagonal elements
array_2d[0,0],array_2d[1,1],array_2d[2,2]

(0, 4, 8)

In [17]:
rng = default_rng(2022)
test = rng.random(9).reshape(3,3)
test

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [18]:
# grab first 2 rows
test[:2]

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778]])

In [19]:
# grab first column
test[:, 0:1]

array([[0.24742606],
       [0.06066207],
       [0.1108689 ]])

In [20]:
# second ele of third row
test[2,1]

0.04305584439252108

### 2. Arithmetic operations

In [21]:
rng = default_rng(909)
inventory = rng.integers(10,100,10)
inventory

array([13, 70, 66, 37, 11, 46, 80, 64, 90, 28], dtype=int64)

In [22]:
inventory + 2

array([15, 72, 68, 39, 13, 48, 82, 66, 92, 30], dtype=int64)

In [23]:
lists = list(inventory)
lists

[13, 70, 66, 37, 11, 46, 80, 64, 90, 28]

In [24]:
new_list = (x + 2 for x in lists)
list(new_list)


[15, 72, 68, 39, 13, 48, 82, 66, 92, 30]

In [25]:
new = []
for x in lists:
    new.append(x+2)
print(new)

[15, 72, 68, 39, 13, 48, 82, 66, 92, 30]


In [26]:
price = (rng.random(10)*10).round(2)
price

array([9.01, 3.08, 3.6 , 6.76, 1.6 , 9.26, 8.98, 0.52, 1.72, 1.  ])

In [27]:
(price * inventory).sum()

2198.4900000000002

In [28]:
prices = np.array([5.99, 6.99, 22.49 ,99.99, 4.99, 49.99])
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [29]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [30]:
rng = default_rng(2022)
test = rng.random(9).reshape(3,3)
test

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])

In [31]:
discount_pc= test[0:2,]
final = 1- discount_pc
fen = final.reshape(6)
print(fen)
#fin = final.flatten() 

[0.75257394 0.90700994 0.38823663 0.93933793 0.33896657 0.24484222]


In [32]:
(total * fen).round(2)

array([ 8.27, 10.88, 10.67, 98.62,  3.39, 13.46])